spring:
  application:
    name: back-auth

server:
  port: 9000
  
  datasource:
    url: jdbc:postgresql://localhost:5432/crm?currentSchema=security&useSSL=false
    username: crm_1
    password: BVfBymMVpTVZ
    driver-class-name: org.postgresql.Driver
    
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  hbm2ddl:
    auto: update
