server:
  port: 9000

spring:
  application:
    name: back-auth
  datasource:
    url: jdbc:postgresql://51.68.44.179:5432/crm?currentSchema=security&useSSL=false
    username: crm_1
    password: BVfBymMVpTVZ
    driver-class-name: org.postgresql.Driver
  jpa:    
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      hbm2ddl:
        auto: update
